# Generated by Django 4.2.5 on 2023-10-12 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=170, verbose_name='ЧПУРЛ')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(upload_to='', verbose_name='превью')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2023, 10, 12, 14, 59, 3, 804228, tzinfo=datetime.timezone.utc), verbose_name='дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('views', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
