# Generated by Django 4.2.5 on 2023-10-13 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_create_at_alter_blog_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 9, 22, 47, 41435, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=170, unique=True, verbose_name='ЧПУРЛ'),
        ),
    ]
