# Generated by Django 4.2.5 on 2023-10-28 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_create_at_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 13, 3, 48, 582489, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
