# Generated by Django 4.2.5 on 2023-11-01 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 12, 23, 9, 64187, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
