# Generated by Django 4.2.5 on 2023-09-28 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='begin_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 28, 12, 13, 42, 480834, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 28, 12, 13, 42, 481447, tzinfo=datetime.timezone.utc), verbose_name='Дата последнего изменения'),
        ),
    ]
