# Generated by Django 4.2.5 on 2023-10-28 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 15, 25, 38, 340518, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 15, 25, 38, 340929, tzinfo=datetime.timezone.utc), verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.IntegerField(default=1, verbose_name='версия'),
        ),
    ]
