# Generated by Django 4.2.5 on 2023-11-03 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_product_created_at_alter_version_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 9, 35, 56, 961340, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
