# Generated by Django 4.2.5 on 2023-11-03 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 3, 31, 761708, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
