# Generated by Django 4.2.5 on 2023-11-04 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_owner_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 13, 8, 53, 508179, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
